---
abstract: 'Sane session affinity (sticky sessions) for Perlbal'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perlbal-Plugin-SessionAffinity
no_index:
  file:
    - README.pod
requires:
  CGI::Cookie: 0
  Digest::SHA: 0
  Hash::Util: 0
  Perlbal: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/xsawyerx/perlbal-plugin-sessionaffinity/issues
  repository: http://github.com/xsawyerx/perlbal-plugin-sessionaffinity
version: 0.010
